source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'rails-api'

gem 'hirb', '~> 0.7.3'

gem 'mysql'

gem 'prawn'
gem 'prawn-table'

gem 'json'

gem 'jwt'
gem 'bcrypt', '~> 3.1', '>= 3.1.11'

gem 'rack-cors', require: 'rack/cors'

group :development, :test do
  gem 'spring'
  gem 'byebug'

  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails', '4.5.0'
  gem 'database_cleaner', '1.4.1'
  gem 'test-unit'
  gem 'shoulda-matchers', require: false
end
